services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    ports:
      - "8545:8545"
    restart: unless-stopped
    entrypoint:
      - anvil
    command:
      - --host=0.0.0.0
      - --fork-url=https://reth-ethereum.ithaca.xyz/rpc
      - --block-time=2